name: Build Prod

on:
  push:
    branches: ["main"]
    tags: ["v*"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_HASH=ghcr.io/$OWNER/larsucll:${{ github.sha }}
          docker build -t $IMAGE_HASH .
          docker push $IMAGE_HASH

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            IMAGE_VERSION=ghcr.io/$OWNER/larsucll:${{ github.ref_name }}
            docker tag $IMAGE_HASH $IMAGE_VERSION
            docker push $IMAGE_VERSION
          fi
